name: 'Terrafir Plan Assessment'
description: 'Assess the plan file for security vulnerabilities'
inputs:
  api-key: 
    description: 'API key for Terrafir'
    required: true
  email: 
    description: 'Email for Terrafir'
    required: true
  plan-file:
    description: 'Path to the terraform plan file'

outputs:
  time:
    description: 'The time plan was assessed' #TODO
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.api-key }}
    - ${{ inputs.email }}
    - ${{ inputs.plan-file }}
